name: TERRAFORM WORKSPACE

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-workspace:
    uses: nuvibit/github-workflows/.github/workflows/terraform_workspace.yaml@main
    secrets:
      GH_SA_TOKEN_RO: ${{ secrets.GH_SA_TOKEN_RO }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
